export const NAMESPACE = 'GAME'
export const CARD_SELECTED = 'CARD_SELECTED'
export const DELETE_GAME = 'DELETE_GAME'
export const NEW_GAME = 'NEW_GAME'
export const CARDS_MATCH = 'CARDS_MATCH'
export const CARDS_MISMATCH = 'CARDS_MISMATCH'
